### PR TITLE
Fix 78: Serializer.encode throws for null and undefined

### LINKED ISSUE #78: `Serializer.encode` throws when serializing null or undefined
When serializing anything with a null or undefined value, `Serializer.encode` throws an error:
```
Uncaught TypeError: Cannot read properties of null (reading 'Symbol(__boxed_type__)')

Uncaught TypeError: Cannot read properties of undefined (reading 'Symbol(__boxed_type__)')
```

---

Now, it's arguable whether support of undefined/null should be supported, but this is a regression from previous behaviour. As can be seen [at this prior commit](https://github.com/swan-io/boxed/blob/9d9c6b232a4dcc38201fb7fc083f5264a38735d3/src/Serializer.ts#L7-L34), there was an explicit null check which dropped the value from serialization, and undefined would fall through and get dropped as per normal.

In the new version [at this current commit](https://github.com/swan-io/boxed/blob/d3a5cbd01fad350f14e2e71adba7114f7e8375df/src/Serializer.ts#L8-L13) null is not explicitly dropped, and undefined cannot fall through.

### PR DESCRIPTION
**Pull request by nobrayner**
This resolves #78.

This does diverge from previous behavior by encoding null.

### CODE REVIEW

**Comment by nobrayner** [comment]
I made the decision to encode null based on my own usage: Retrieving data using Prisma ORM in which nullable database columns are returned as null.

I see it as too much maintenance effort to have to convert each nullable column into an Option, especially in an existing codebase where most usages expect `T | null` as the type.

This approach also brings `encode` in line with `decode`, which explicitly handles parsing null.

File: src/Serializer.ts [hunk 1]
```diff
@@ -6,7 +6,7 @@ export const encode = (value: any, indent?: number | undefined) => {
   return JSON.stringify(
     value,
     (key, value) => {
-      if (typeof value[BOXED_TYPE] === "string") {
+      if (typeof value?.[BOXED_TYPE] === "string") {
```
Comment (bloodyowl) [inline src/Serializer.ts:9]: let's maybe rather use the following to maximize browser compatibility

```
if (value == null) {
  return value
}
```

**Review by bloodyowl — COMMENTED** [review]
thanks for your PR! made a small comment

File: src/Serializer.ts (hunk 1 above)
Comment (nobrayner) [reply src/Serializer.ts:9]: It's been a while since I had to think about syntax support of older browsers! 😅 

I had a niggling that the Typescript compiler actually compiled out optional chaining - depending on the build target - and ran a test build. It did indeed turn the optional chaining into the following:
```ts
null==n?n:"string"==typeof n[o]
```

Then to _really_ satisfy my curiosity, I tried your suggestion and it actually compiled to the exact same output!

**Review by bloodyowl — APPROVED** [review]

**Comment by bloodyowl** [comment]
thanks for your PR! available in v2.3.1
